package visualization.javaFxMaps;

import model.outputData.OutputData;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static config.VisualizationConfig.*;

public class GenerateJSSettings {
    private static GenerateJSSettings instance;

    private GenerateJSSettings() {}

    public static GenerateJSSettings getInstance() {
        if(instance == null)
            instance = new GenerateJSSettings();
        return instance;
    }

    public void generateSettings(OutputData grid) {
        List<String> lines = new ArrayList<>();
        lines.add("// settings.js generated by GenerateJSSettings.java");
        lines.add("var latitude = " + ((LATITUDE_START + LATITUDE_END) / 2) + ";");
        lines.add("var longitude = " + ((LONGITUDE_START + LONGITUDE_END) / 2) + ";");
        lines.add("var zoom = " + ZOOM + ";");
        lines.add("var max_flights = " + grid.getMaxTotalRegisteredFlightCount() + ";");
        lines.add("var alphaProperty = \"" + ALPHA_PROPERTY + "\";");
        StringBuilder displayPropertiesString = new StringBuilder("var displayProperties = [");
        for(int i = 0; i < DISPLAY_PROPERTIES.length; i++) {
            displayPropertiesString.append("\"");
            displayPropertiesString.append(DISPLAY_PROPERTIES[i]);
            displayPropertiesString.append("\"");
            if(i < DISPLAY_PROPERTIES.length - 1)
                displayPropertiesString.append(", ");
        }
        displayPropertiesString.append("];");
        lines.add(displayPropertiesString.toString());
        lines.add("var minimumAlpha = " + MINIMUM_ALPHA + ";");
        lines.add("var displayStringFormat = \"" + DISPLAY_STRING_FORMAT + "\";");
        lines.add("var visibilityFactor = \"" + VISIBILITY_FACTOR + "\";");

        try {
            Path file = Paths.get("src/visualization/javaFxMaps/settings.js");
            Files.write(file, lines, Charset.forName("UTF-8"));
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }
}
