// settings.js generated by GenerateJSSettings.java
var latitude = 56.0;
var longitude = 9.5;
var zoom = 7;
var max_flights = 689;
var alphaProperty = "flights";
var hoverProperty1 = "thermals";
var hoverProperty2 = "flights";
var minimumAlpha = 0.3;
