// settings.js generated by GenerateJSSettings.java
var latitude = 56.0;
var longitude = 9.5;
var zoom = 7;
var max_flights = 208;
var alphaProperty = "flights";
var displayProperties = ["thermals", "flights"];
var minimumAlpha = 0.3;
var displayStringFormat = "T:@1 / F:@2";
