BEGIN DROP_INDEX('INDEX_TO_D_TIME_HOUR'); END;
/
BEGIN DROP_INDEX('INDEX_TO_D_TIME_MINUTE'); END;
/
BEGIN DROP_INDEX('INDEX_TO_D_TIME_SECOND'); END;
/

CREATE INDEX INDEX_TO_D_TIME_HOUR on  TRANSFORM_IGC_EMPTY_GLIDER_REGNO(to_char(TIME_OF_LOG, 'HH24'));
CREATE INDEX INDEX_TO_D_TIME_MINUTE on TRANSFORM_IGC_EMPTY_GLIDER_REGNO(to_char(TIME_OF_LOG, 'MI'));
CREATE INDEX INDEX_TO_D_TIME_SECOND on TRANSFORM_IGC_EMPTY_GLIDER_REGNO(to_char(TIME_OF_LOG, 'SS'));

BEGIN DROP_SEQUENCE('glider_surr_key'); END;
/

create SEQUENCE glider_surr_key
  START WITH 1
  INCREMENT BY 1
  CACHE 100
  NOMAXVALUE
;

COMMIT;
